# Form implementation generated from reading ui file 'delete_student.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(370, 156)
        Dialog.setMinimumSize(QtCore.QSize(370, 156))
        Dialog.setMaximumSize(QtCore.QSize(370, 156))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.verticalLayout.addWidget(self.header_label)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.id_number_label = QtWidgets.QLabel(parent=self.frame)
        self.id_number_label.setMinimumSize(QtCore.QSize(100, 0))
        self.id_number_label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_number_label.setFont(font)
        self.id_number_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.id_number_label.setObjectName("id_number_label")
        self.horizontalLayout.addWidget(self.id_number_label)
        spacerItem = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.student_to_delete_combobox = QtWidgets.QComboBox(parent=self.frame)
        self.student_to_delete_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.student_to_delete_combobox.setFont(font)
        self.student_to_delete_combobox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.student_to_delete_combobox.setEditable(True)
        self.student_to_delete_combobox.setObjectName("student_to_delete_combobox")
        self.student_to_delete_combobox.addItem("")
        self.horizontalLayout.addWidget(self.student_to_delete_combobox)
        self.verticalLayout.addWidget(self.frame)
        self.delete_student_button = QtWidgets.QPushButton(parent=Dialog)
        self.delete_student_button.setEnabled(False)
        self.delete_student_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.delete_student_button.setFont(font)
        self.delete_student_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_student_button.setObjectName("delete_student_button")
        self.verticalLayout.addWidget(self.delete_student_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Delete a student"))
        self.header_label.setText(_translate("Dialog", "Select a student to delete"))
        self.id_number_label.setText(_translate("Dialog", "ID Number"))
        self.student_to_delete_combobox.setItemText(0, _translate("Dialog", "--Select ID Number--"))
        self.delete_student_button.setText(_translate("Dialog", "Delete student"))
